#define SQLITE_CORE
#include <sqlite3.h>
#include "../../include/sqlite3_value.hpp"
#include <cstdio>
#include <cassert>
#include <cstring>
#include <map>
#include <unordered_map>
#include <string>

// ============================================================================
// Transparent Hashing & std::map Heterogeneous Lookup Tests
// ============================================================================
void test_transparent_hashing(sqlite3* db) {
    printf("Testing Transparent Hashing (SqliteValueHash & SqliteValueEqual)...\n");

    SqliteValueHash hasher;
    SqliteValueEqual eq;

    // 1. Prepare SQLite values from a statement
    sqlite3_stmt* stmt = nullptr;
    assert(sqlite3_prepare_v2(db, "SELECT 42, 'alice', 'bob_very_long_name_exceeding_13_chars', 3.14;", -1, &stmt, nullptr) == SQLITE_OK);
    assert(sqlite3_step(stmt) == SQLITE_ROW);

    SqliteValueView v_int = SqliteValueView::from_column(stmt, 0);
    SqliteValueView v_alice = SqliteValueView::from_column(stmt, 1);
    SqliteValueView v_bob = SqliteValueView::from_column(stmt, 2);
    SqliteValueView v_pi = SqliteValueView::from_column(stmt, 3);

    SqliteValueOwned o_int(42LL);
    SqliteValueOwned o_alice = SqliteValueOwned::from_text("alice");
    SqliteValueOwned o_bob = v_bob.to_owned();
    SqliteValueOwned o_pi(3.14);

    SqliteStringView str_alice("alice", 5);

    // 2. Verify exact mathematical hash equivalence across all representations
    assert(hasher(o_int) == hasher(v_int));
    assert(hasher(o_int) == hasher(42LL));
    assert(hasher(o_int) == hasher(42));

    assert(hasher(o_alice) == hasher(v_alice));
    assert(hasher(o_alice) == hasher(str_alice));
    assert(hasher(o_alice) == hasher("alice"));

    assert(hasher(o_bob) == hasher(v_bob));
    assert(hasher(o_pi) == hasher(v_pi));
    assert(hasher(o_pi) == hasher(3.14));

    // 3. Verify transparent equality
    assert(eq(o_int, v_int));
    assert(eq(o_int, 42LL));
    assert(eq(v_int, 42LL));

    assert(eq(o_alice, v_alice));
    assert(eq(o_alice, str_alice));
    assert(eq(o_alice, "alice"));
    assert(eq(v_alice, str_alice));
    assert(eq(v_alice, "alice"));

    // Verify SqliteString, SqliteBuffer, and SqliteBufferSlice hashing and equality
    SqliteString s_alice("alice");
    SqliteBuffer b_alice("alice", 5);
    SqliteBufferSlice sl_alice("alice", 5);

    assert(hasher(o_alice) == hasher(s_alice));
    assert(hasher(o_alice) == hasher(b_alice));
    assert(hasher(o_alice) == hasher(sl_alice));

    assert(eq(o_alice, s_alice));
    assert(eq(s_alice, o_alice));
    assert(eq(v_alice, s_alice));
    assert(eq(s_alice, v_alice));

    // In SQLite type hierarchy: TEXT != BLOB, and TEXT < BLOB
    assert(!eq(o_alice, b_alice));
    assert(o_alice != b_alice);
    assert(o_alice < b_alice);
    assert(b_alice > o_alice);

    // Matching BLOB value
    SqliteValueOwned o_blob = SqliteValueOwned::from_blob("alice", 5);
    assert(eq(o_blob, b_alice));
    assert(eq(b_alice, o_blob));
    assert(eq(o_blob, sl_alice));
    assert(eq(sl_alice, o_blob));

    // 4. Heterogeneous Map Lookup with std::less<>
    std::map<SqliteValueOwned, int, std::less<>> map;
    map[SqliteValueOwned(42LL)] = 100;
    map[SqliteValueOwned::from_text("alice")] = 200;
    map[v_bob.to_owned()] = 300;
    map[SqliteValueOwned(3.14)] = 400;
    map[SqliteValueOwned::from_blob("alice", 5)] = 500;

    assert(map.find(v_int) != map.end());
    assert(map.find(v_int)->second == 100);

    assert(map.find(v_alice) != map.end());
    assert(map.find(v_alice)->second == 200);

    assert(map.find(str_alice) != map.end());
    assert(map.find(str_alice)->second == 200);

    assert(map.find(s_alice) != map.end());
    assert(map.find(s_alice)->second == 200);

    assert(map.find(b_alice) != map.end());
    assert(map.find(b_alice)->second == 500);

    assert(map.find(sl_alice) != map.end());
    assert(map.find(sl_alice)->second == 500);

    assert(map.find("alice") != map.end());
    assert(map.find("alice")->second == 200);

    assert(map.find(42LL) != map.end());
    assert(map.find(42LL)->second == 100);

    sqlite3_finalize(stmt);
}

// ============================================================================
// NEW TESTS FOR UPDATED sqlite3_value.hpp
// ============================================================================

/**
 * @brief Tests SqliteValueHash overloads for float, bool, uint32_t, uint64_t.
 *        These overloads are generated by SQLITE_DERIVE_TRANSPARENT_SCALAR_HASH_OVERLOADS.
 */
void test_hash_scalar_overloads() {
    printf("Testing SqliteValueHash Scalar Overloads (float, bool, uint32_t, uint64_t)...\n");

    SqliteValueHash hasher;

    // float: internally promotes to double for hashing
    float f = 2.5f;
    SqliteValueOwned val_f(static_cast<double>(f));
    assert(hasher(f) == hasher(static_cast<double>(f)));
    assert(hasher(f) == hasher(val_f));

    // bool: maps to int64 (0 or 1)
    SqliteValueOwned val_true(true);
    SqliteValueOwned val_false(false);
    assert(hasher(true)  == hasher(val_true));
    assert(hasher(false) == hasher(val_false));
    assert(hasher(true)  != hasher(false)); // must differ

    // uint32_t: maps to int64
    uint32_t u32 = 999u;
    SqliteValueOwned val_u32(static_cast<sqlite3_int64>(u32));
    assert(hasher(u32) == hasher(val_u32));
    assert(hasher(u32) == hasher(static_cast<sqlite3_int64>(u32)));

    // uint64_t: independent hash (not promoted via int64 path)
    uint64_t u64 = 9999999999ULL;
    SqliteValueOwned val_u64(static_cast<sqlite3_int64>(u64));
    assert(hasher(u64) == hasher(val_u64));

    // Hash stability: same value always produces same hash
    assert(hasher(42.0) == hasher(42.0));
    assert(hasher(true) == hasher(true));
    assert(hasher(false) == hasher(false));
    assert(hasher(u32) == hasher(u32));
}

/**
 * @brief Tests std::unordered_map with SqliteValueHash and SqliteValueEqual
 *        for fully heterogeneous insert and lookup.
 */
void test_unordered_map_heterogeneous(sqlite3* db) {
    printf("Testing std::unordered_map Heterogeneous Lookups (SqliteValueHash + SqliteValueEqual)...\n");

    std::unordered_map<SqliteValueOwned, int, SqliteValueHash, SqliteValueEqual> umap;

    // Insert mixed types
    umap[SqliteValueOwned(100LL)]                  = 1;
    umap[SqliteValueOwned::from_text("hello")]      = 2;
    umap[SqliteValueOwned(3.14)]                   = 3;
    umap[SqliteValueOwned::from_text("a long string beyond 13 chars")] = 4;

    // Look up by SqliteValueView (zero-copy)
    sqlite3_stmt* stmt = nullptr;
    assert(sqlite3_prepare_v2(db,
        "SELECT 100, 'hello', 3.14, 'a long string beyond 13 chars';",
        -1, &stmt, nullptr) == SQLITE_OK);
    assert(sqlite3_step(stmt) == SQLITE_ROW);

    SqliteValueView v_int   = SqliteValueView::from_column(stmt, 0);
    SqliteValueView v_text  = SqliteValueView::from_column(stmt, 1);
    SqliteValueView v_float = SqliteValueView::from_column(stmt, 2);
    SqliteValueView v_long  = SqliteValueView::from_column(stmt, 3);

    // Verify hasher and equality directly on views vs literals
    SqliteValueHash hasher;
    SqliteValueEqual eq;
    assert(hasher(v_int) == hasher(100LL));
    assert(eq(v_int, 100LL));
    assert(hasher(v_text) == hasher("hello"));
    assert(eq(v_text, "hello"));

    // Standard find with key_type in C++14:
    assert(umap.find(SqliteValueOwned(100LL)) != umap.end() && umap.find(SqliteValueOwned(100LL))->second == 1);
    assert(umap.find(v_int.to_owned()) != umap.end() && umap.find(v_int.to_owned())->second == 1);
    assert(umap.find(SqliteValueOwned::from_text("hello")) != umap.end() && umap.find(SqliteValueOwned::from_text("hello"))->second == 2);
    assert(umap.find(v_text.to_owned()) != umap.end() && umap.find(v_text.to_owned())->second == 2);
    assert(umap.find(SqliteValueOwned(3.14)) != umap.end() && umap.find(SqliteValueOwned(3.14))->second == 3);
    assert(umap.find(v_float.to_owned()) != umap.end() && umap.find(v_float.to_owned())->second == 3);
    assert(umap.find(v_long.to_owned()) != umap.end() && umap.find(v_long.to_owned())->second == 4);

    assert(umap.find(SqliteValueOwned(99LL)) == umap.end());
    assert(umap.find(SqliteValueOwned::from_text("world")) == umap.end());

#if __cplusplus >= 202002L
    // C++20 heterogeneous find: View & literals -> key
    assert(umap.find(v_int)   != umap.end() && umap.find(v_int)->second   == 1);
    assert(umap.find(v_text)  != umap.end() && umap.find(v_text)->second  == 2);
    assert(umap.find(v_float) != umap.end() && umap.find(v_float)->second == 3);
    assert(umap.find(v_long)  != umap.end() && umap.find(v_long)->second  == 4);
    assert(umap.find(100LL)   != umap.end() && umap.find(100LL)->second   == 1);
    assert(umap.find("hello") != umap.end() && umap.find("hello")->second == 2);
    assert(umap.find(99LL)    == umap.end());
    assert(umap.find("world") == umap.end());
#endif

    sqlite3_finalize(stmt);
}

/**
 * @brief Tests SqliteValueLess transparent functor as the comparator in std::map.
 */
void test_sqlite_value_less_functor() {
    printf("Testing SqliteValueLess Transparent Functor (std::map comparator)...\n");

    SqliteValueLess less;

    // NULL < INTEGER < FLOAT < TEXT < BLOB type ordering
    SqliteValueOwned null_val;
    SqliteValueOwned int_val(1LL);
    SqliteValueOwned float_val(1.0);
    SqliteValueOwned text_val("a");
    char bd[] = {0x01};
    SqliteValueOwned blob_val(SqliteBlobView(bd, 1));

    assert( less(null_val, int_val));
    assert(!less(int_val, null_val));
    assert( less(null_val, text_val));
    assert( less(null_val, blob_val));
    assert( less(int_val, text_val));
    assert( less(text_val, blob_val));

    // Strict typing tie-breaker: int(1) < float(1.0) within NUMERIC rank
    assert( less(int_val, float_val));
    assert(!less(float_val, int_val));

    // Same type, same value → not less
    assert(!less(int_val, int_val));
    assert(!less(null_val, null_val));

    // Use SqliteValueLess in std::map
    std::map<SqliteValueOwned, const char*, SqliteValueLess> ordered_map;
    ordered_map[SqliteValueOwned(10LL)]              = "ten";
    ordered_map[SqliteValueOwned(5LL)]               = "five";
    ordered_map[SqliteValueOwned::from_text("bar")]  = "bar_val";
    ordered_map[SqliteValueOwned::from_text("foo")]  = "foo_val";

    // Verify ordering: 5 < 10 < "bar" < "foo"
    auto it = ordered_map.begin();
    assert(it->first == 5LL);    ++it;
    assert(it->first == 10LL);   ++it;
    assert(it->first == "bar");  ++it;
    assert(it->first == "foo");
}

/**
 * @brief Tests SqliteValueEqual transparent functor across all type combinations.
 */
void test_sqlite_value_equal_functor(sqlite3* db) {
    printf("Testing SqliteValueEqual Transparent Functor (Heterogeneous Equality)...\n");

    SqliteValueEqual eq;

    // int vs view
    sqlite3_stmt* stmt = nullptr;
    assert(sqlite3_prepare_v2(db, "SELECT 42, 'hello', 3.14;", -1, &stmt, nullptr) == SQLITE_OK);
    assert(sqlite3_step(stmt) == SQLITE_ROW);

    SqliteValueView v_int   = SqliteValueView::from_column(stmt, 0);
    SqliteValueView v_text  = SqliteValueView::from_column(stmt, 1);
    SqliteValueView v_float = SqliteValueView::from_column(stmt, 2);

    SqliteValueOwned o_int(42LL);
    SqliteValueOwned o_text  = SqliteValueOwned::from_text("hello");
    SqliteValueOwned o_float(3.14);

    // Owned == Owned
    assert(eq(o_int, o_int));
    assert(eq(o_text, o_text));
    assert(!eq(o_int, o_text));

    // Owned == View
    assert(eq(o_int, v_int));
    assert(eq(o_text, v_text));
    assert(eq(o_float, v_float));

    // View == Owned (symmetric)
    assert(eq(v_int, o_int));
    assert(eq(v_text, o_text));

    // Primitive comparisons via functor
    assert(eq(o_int, 42LL));
    assert(eq(v_int, 42LL));
    assert(eq(o_text, "hello"));
    assert(eq(v_text, "hello"));

    // Type mismatch → not equal
    assert(!eq(o_int, 42.0));   // INTEGER != FLOAT
    assert(!eq(o_int, "42"));   // INTEGER != TEXT
    assert(!eq(o_text, o_float));

    sqlite3_finalize(stmt);
}

/**
 * @brief Tests std::unordered_map and std::map heterogeneous lookups with UUIDs.
 */
void test_uuid_std_heterogeneous_lookup(sqlite3* db) {
    printf("Testing UUID Heterogeneous STL Lookup (std::unordered_map & std::map)...\n");

    const uint8_t raw_uuid1[16] = {
        0x55, 0x0e, 0x84, 0x00, 0xe2, 0x9b, 0x41, 0xd4,
        0xa7, 0x16, 0x44, 0x66, 0x55, 0x44, 0x00, 0x00
    };
    const uint8_t raw_uuid2[16] = {
        0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0,
        0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88
    };

    SqliteValueOwned u_bin_std = SqliteValueOwned::from_uuid(raw_uuid1, SqliteUuidUtil::UUID_FORMAT_STANDARD);
    SqliteValueOwned u_bin_upper = SqliteValueOwned::from_uuid(raw_uuid1, static_cast<SqliteUuidUtil::UuidFormatFlags>(SqliteUuidUtil::UUID_FORMAT_STANDARD | SqliteUuidUtil::UUID_FORMAT_UPPERCASE));
    SqliteValueOwned u_bin_blob = SqliteValueOwned::from_uuid(raw_uuid1, SqliteUuidUtil::UUID_FORMAT_BLOB);

    SqliteValueOwned u_bin2 = SqliteValueOwned::from_uuid(raw_uuid2, SqliteUuidUtil::UUID_FORMAT_STANDARD);

    // 1. std::unordered_map with heterogeneous lookup
    std::unordered_map<SqliteValueOwned, std::string, SqliteValueHash, SqliteValueEqual> uuid_map;
    uuid_map[u_bin_std] = "uuid1_entity";
    uuid_map[u_bin2] = "uuid2_entity";

    assert(uuid_map.size() == 2);

    // Look up uuid1 via different representations of the same UUID
    SqliteValueOwned q_text_std = SqliteValueOwned::from_uuid("550e8400-e29b-41d4-a716-446655440000");
    SqliteValueOwned q_text_upper = SqliteValueOwned::from_uuid("550E8400-E29B-41D4-A716-446655440000");
    SqliteValueOwned q_text_blob = SqliteValueOwned::from_uuid("550e8400e29b41d4a716446655440000");

    assert(uuid_map.find(q_text_std) != uuid_map.end());
    assert(uuid_map.find(q_text_std)->second == "uuid1_entity");

    assert(uuid_map.find(q_text_upper) != uuid_map.end());
    assert(uuid_map.find(q_text_upper)->second == "uuid1_entity");

    assert(uuid_map.find(q_text_blob) != uuid_map.end());
    assert(uuid_map.find(q_text_blob)->second == "uuid1_entity");

    assert(uuid_map.find(u_bin_blob) != uuid_map.end());
    assert(uuid_map.find(u_bin_blob)->second == "uuid1_entity");

    assert(uuid_map.find(u_bin_upper) != uuid_map.end());
    assert(uuid_map.find(u_bin_upper)->second == "uuid1_entity");

    // Look up via SqliteValueView from database column
    sqlite3_stmt* stmt = nullptr;
    assert(sqlite3_prepare_v2(db, "SELECT '550e8400-e29b-41d4-a716-446655440000', '550E8400-E29B-41D4-A716-446655440000';", -1, &stmt, nullptr) == SQLITE_OK);
    assert(sqlite3_step(stmt) == SQLITE_ROW);
    SqliteValueView view_std = SqliteValueView::from_column(stmt, 0);
    SqliteValueView view_upper = SqliteValueView::from_column(stmt, 1);

    assert(view_std.as_text() == "550e8400-e29b-41d4-a716-446655440000");
    assert(view_upper.as_text() == "550E8400-E29B-41D4-A716-446655440000");

    SqliteValueOwned owned_from_view_std = SqliteValueOwned::from_uuid(view_std.as_text().data());
    SqliteValueOwned owned_from_view_upper = SqliteValueOwned::from_uuid(view_upper.as_text().data());

    assert(uuid_map.find(owned_from_view_std) != uuid_map.end());
    assert(uuid_map.find(owned_from_view_std)->second == "uuid1_entity");
    assert(uuid_map.find(owned_from_view_upper) != uuid_map.end());
    assert(uuid_map.find(owned_from_view_upper)->second == "uuid1_entity");

    sqlite3_finalize(stmt);
}

void test_datetime_std_heterogeneous_lookup(sqlite3* db) {
    printf("Testing Datetime STL Heterogeneous Lookup (std::unordered_map & std::map)...\n");

    const sqlite3_int64 epoch1 = 1725450000000LL;
    const sqlite3_int64 epoch2 = 1788500000000LL;
    const char* iso_ts_std = "2026-09-04 17:20:00.000";
    const char* iso_ts_full = "2026-09-04T17:20:00.123456Z";
    const char* iso_ts_tz = "2026-09-04T17:20:00+05:30";

    SqliteValueOwned dt1 = SqliteValueOwned::from_datetime(epoch1);
    SqliteValueOwned dt2 = SqliteValueOwned::from_datetime(epoch2);
    SqliteValueOwned dt_text = SqliteValueOwned::from_datetime(iso_ts_std);
    SqliteValueOwned dt_full = SqliteValueOwned::from_datetime(iso_ts_full);
    SqliteValueOwned dt_tz = SqliteValueOwned::from_datetime(iso_ts_tz);

    // 1. Verify Direct Transparent Hasher & Equality
    SqliteValueHash hasher;
    SqliteValueEqual eq;
    assert(hasher(dt1) == hasher(epoch1));
    assert(eq(dt1, epoch1));
    assert(hasher(dt_text) == hasher(iso_ts_std));
    assert(eq(dt_text, iso_ts_std));
    assert(hasher(dt_full) == hasher(iso_ts_full));
    assert(eq(dt_full, iso_ts_full));
    assert(hasher(dt_tz) == hasher(iso_ts_tz));
    assert(eq(dt_tz, iso_ts_tz));

    // 2. std::unordered_map with SqliteValueHash and SqliteValueEqual
    std::unordered_map<SqliteValueOwned, std::string, SqliteValueHash, SqliteValueEqual> dt_map;
    dt_map[dt1] = "session_start";
    dt_map[dt2] = "session_future";
    dt_map[dt_text] = "session_iso";
    dt_map[dt_full] = "session_full_iso";
    dt_map[dt_tz] = "session_tz_iso";

    assert(dt_map.size() == 5);

    // Lookup using SqliteValueOwned
    assert(dt_map.find(SqliteValueOwned(epoch1)) != dt_map.end());
    assert(dt_map.find(SqliteValueOwned(epoch1))->second == "session_start");

    assert(dt_map.find(SqliteValueOwned(epoch2)) != dt_map.end());
    assert(dt_map.find(SqliteValueOwned(epoch2))->second == "session_future");

    assert(dt_map.find(SqliteValueOwned::from_text(iso_ts_std)) != dt_map.end());
    assert(dt_map.find(SqliteValueOwned::from_text(iso_ts_std))->second == "session_iso");

    assert(dt_map.find(SqliteValueOwned::from_datetime(iso_ts_full)) != dt_map.end());
    assert(dt_map.find(SqliteValueOwned::from_datetime(iso_ts_full))->second == "session_full_iso");

    assert(dt_map.find(SqliteValueOwned::from_datetime(iso_ts_tz)) != dt_map.end());
    assert(dt_map.find(SqliteValueOwned::from_datetime(iso_ts_tz))->second == "session_tz_iso");

#if __cplusplus >= 202002L
    // C++20 Heterogeneous unordered_map lookup
    assert(dt_map.find(epoch1) != dt_map.end());
    assert(dt_map.find(epoch1)->second == "session_start");
    assert(dt_map.find(SqliteStringView(iso_ts_std, strlen(iso_ts_std))) != dt_map.end());
#endif

    // 3. std::map with std::less<> (C++14 Heterogeneous Lookup)
    std::map<SqliteValueOwned, std::string, std::less<>> dt_ordered;
    dt_ordered[dt1] = "start";
    dt_ordered[dt2] = "future";
    dt_ordered[dt_text] = "text_date";
    dt_ordered[dt_full] = "full_date";
    dt_ordered[dt_tz] = "tz_date";

    // Heterogeneous Lookup via primitive and string view in std::map (C++14 standard)
    SqliteStringView sv_std(iso_ts_std, strlen(iso_ts_std));
    SqliteStringView sv_full(iso_ts_full, strlen(iso_ts_full));
    SqliteStringView sv_tz(iso_ts_tz, strlen(iso_ts_tz));
    assert(dt_ordered.find(epoch1) != dt_ordered.end());
    assert(dt_ordered.find(epoch1)->second == "start");
    assert(dt_ordered.find(sv_std) != dt_ordered.end());
    assert(dt_ordered.find(sv_std)->second == "text_date");
    assert(dt_ordered.find(sv_full) != dt_ordered.end());
    assert(dt_ordered.find(sv_full)->second == "full_date");
    assert(dt_ordered.find(sv_tz) != dt_ordered.end());
    assert(dt_ordered.find(sv_tz)->second == "tz_date");

    // Range queries
    auto it_lb = dt_ordered.lower_bound(epoch1);
    assert(it_lb != dt_ordered.end());
    assert(it_lb->first.as_int64() == epoch1);

    // 4. Database column view lookup with std::map
    sqlite3_stmt* stmt = nullptr;
    assert(sqlite3_prepare_v2(db, "SELECT 1725450000000, '2026-09-04 17:20:00.000', '2026-09-04T17:20:00.123456Z';", -1, &stmt, nullptr) == SQLITE_OK);
    assert(sqlite3_step(stmt) == SQLITE_ROW);
    SqliteValueView v_epoch = SqliteValueView::from_column(stmt, 0);
    SqliteValueView v_text = SqliteValueView::from_column(stmt, 1);
    SqliteValueView v_full = SqliteValueView::from_column(stmt, 2);

    assert(dt_ordered.find(v_epoch) != dt_ordered.end());
    assert(dt_ordered.find(v_epoch)->second == "start");

    assert(dt_ordered.find(v_text) != dt_ordered.end());
    assert(dt_ordered.find(v_text)->second == "text_date");

    assert(dt_ordered.find(v_full) != dt_ordered.end());
    assert(dt_ordered.find(v_full)->second == "full_date");

    sqlite3_finalize(stmt);
}

int main() {
    printf("================================================================\n");
    printf("RUNNING SQLITE VALUE STD TESTS (Transparent Hashing & STL Map)\n");
    printf("================================================================\n");

    sqlite3_initialize();
    sqlite3* db = nullptr;
    assert(sqlite3_open(":memory:", &db) == SQLITE_OK);

    test_transparent_hashing(db);

    // NEW TESTS
    test_hash_scalar_overloads();
    test_unordered_map_heterogeneous(db);
    test_sqlite_value_less_functor();
    test_sqlite_value_equal_functor(db);
    test_uuid_std_heterogeneous_lookup(db);
    test_datetime_std_heterogeneous_lookup(db);

    sqlite3_close(db);
    sqlite3_shutdown();

    printf("================================================================\n");
    printf("ALL SQLITE VALUE STD TESTS PASSED SUCCESSFULLY!\n");
    printf("================================================================\n");
    return 0;
}

