#define SQLITE_CORE
#include <sqlite3.h>
#include "../../include/sqlite3_value.hpp"
#include <cstdio>
#include <cassert>
#include <cstring>
#include <map>
#include <unordered_map>

// ============================================================================
// Transparent Hashing & std::map Heterogeneous Lookup Tests
// ============================================================================
void test_transparent_hashing(sqlite3* db) {
    printf("Testing Transparent Hashing (SqliteValueHash & SqliteValueEqual)...\n");

    SqliteValueHash hasher;
    SqliteValueEqual eq;

    // 1. Prepare SQLite values from a statement
    sqlite3_stmt* stmt = nullptr;
    assert(sqlite3_prepare_v2(db, "SELECT 42, 'alice', 'bob_very_long_name_exceeding_13_chars', 3.14;", -1, &stmt, nullptr) == SQLITE_OK);
    assert(sqlite3_step(stmt) == SQLITE_ROW);

    SqliteValueView v_int = SqliteValueView::from_column(stmt, 0);
    SqliteValueView v_alice = SqliteValueView::from_column(stmt, 1);
    SqliteValueView v_bob = SqliteValueView::from_column(stmt, 2);
    SqliteValueView v_pi = SqliteValueView::from_column(stmt, 3);

    SqliteValueOwned o_int(42LL);
    SqliteValueOwned o_alice = SqliteValueOwned::from_text("alice");
    SqliteValueOwned o_bob = v_bob.to_owned();
    SqliteValueOwned o_pi(3.14);

    SqliteStringView str_alice("alice", 5);

    // 2. Verify exact mathematical hash equivalence across all representations
    assert(hasher(o_int) == hasher(v_int));
    assert(hasher(o_int) == hasher(42LL));
    assert(hasher(o_int) == hasher(42));

    assert(hasher(o_alice) == hasher(v_alice));
    assert(hasher(o_alice) == hasher(str_alice));
    assert(hasher(o_alice) == hasher("alice"));

    assert(hasher(o_bob) == hasher(v_bob));
    assert(hasher(o_pi) == hasher(v_pi));
    assert(hasher(o_pi) == hasher(3.14));

    // 3. Verify transparent equality
    assert(eq(o_int, v_int));
    assert(eq(o_int, 42LL));
    assert(eq(v_int, 42LL));

    assert(eq(o_alice, v_alice));
    assert(eq(o_alice, str_alice));
    assert(eq(o_alice, "alice"));
    assert(eq(v_alice, str_alice));
    assert(eq(v_alice, "alice"));

    // 4. Heterogeneous Map Lookup with std::less<>
    std::map<SqliteValueOwned, int, std::less<>> map;
    map[SqliteValueOwned(42LL)] = 100;
    map[SqliteValueOwned::from_text("alice")] = 200;
    map[v_bob.to_owned()] = 300;
    map[SqliteValueOwned(3.14)] = 400;

    assert(map.find(v_int) != map.end());
    assert(map.find(v_int)->second == 100);

    assert(map.find(v_alice) != map.end());
    assert(map.find(v_alice)->second == 200);

    assert(map.find(str_alice) != map.end());
    assert(map.find(str_alice)->second == 200);

    assert(map.find("alice") != map.end());
    assert(map.find("alice")->second == 200);

    assert(map.find(42LL) != map.end());
    assert(map.find(42LL)->second == 100);

    sqlite3_finalize(stmt);
}

// ============================================================================
// NEW TESTS FOR UPDATED sqlite3_value.hpp
// ============================================================================

/**
 * @brief Tests SqliteValueHash overloads for float, bool, uint32_t, uint64_t.
 *        These overloads are generated by SQLITE_DERIVE_TRANSPARENT_SCALAR_HASH_OVERLOADS.
 */
void test_hash_scalar_overloads() {
    printf("Testing SqliteValueHash Scalar Overloads (float, bool, uint32_t, uint64_t)...\n");

    SqliteValueHash hasher;

    // float: internally promotes to double for hashing
    float f = 2.5f;
    SqliteValueOwned val_f(static_cast<double>(f));
    assert(hasher(f) == hasher(static_cast<double>(f)));
    assert(hasher(f) == hasher(val_f));

    // bool: maps to int64 (0 or 1)
    SqliteValueOwned val_true(true);
    SqliteValueOwned val_false(false);
    assert(hasher(true)  == hasher(val_true));
    assert(hasher(false) == hasher(val_false));
    assert(hasher(true)  != hasher(false)); // must differ

    // uint32_t: maps to int64
    uint32_t u32 = 999u;
    SqliteValueOwned val_u32(static_cast<sqlite3_int64>(u32));
    assert(hasher(u32) == hasher(val_u32));
    assert(hasher(u32) == hasher(static_cast<sqlite3_int64>(u32)));

    // uint64_t: independent hash (not promoted via int64 path)
    uint64_t u64 = 9999999999ULL;
    SqliteValueOwned val_u64(static_cast<sqlite3_int64>(u64));
    assert(hasher(u64) == hasher(val_u64));

    // Hash stability: same value always produces same hash
    assert(hasher(42.0) == hasher(42.0));
    assert(hasher(true) == hasher(true));
    assert(hasher(false) == hasher(false));
    assert(hasher(u32) == hasher(u32));
}

/**
 * @brief Tests std::unordered_map with SqliteValueHash and SqliteValueEqual
 *        for fully heterogeneous insert and lookup.
 */
void test_unordered_map_heterogeneous(sqlite3* db) {
    printf("Testing std::unordered_map Heterogeneous Lookups (SqliteValueHash + SqliteValueEqual)...\n");

    std::unordered_map<SqliteValueOwned, int, SqliteValueHash, SqliteValueEqual> umap;

    // Insert mixed types
    umap[SqliteValueOwned(100LL)]                  = 1;
    umap[SqliteValueOwned::from_text("hello")]      = 2;
    umap[SqliteValueOwned(3.14)]                   = 3;
    umap[SqliteValueOwned::from_text("a long string beyond 13 chars")] = 4;

    // Look up by SqliteValueView (zero-copy)
    sqlite3_stmt* stmt = nullptr;
    assert(sqlite3_prepare_v2(db,
        "SELECT 100, 'hello', 3.14, 'a long string beyond 13 chars';",
        -1, &stmt, nullptr) == SQLITE_OK);
    assert(sqlite3_step(stmt) == SQLITE_ROW);

    SqliteValueView v_int   = SqliteValueView::from_column(stmt, 0);
    SqliteValueView v_text  = SqliteValueView::from_column(stmt, 1);
    SqliteValueView v_float = SqliteValueView::from_column(stmt, 2);
    SqliteValueView v_long  = SqliteValueView::from_column(stmt, 3);

    // Verify hasher and equality directly on views vs literals
    SqliteValueHash hasher;
    SqliteValueEqual eq;
    assert(hasher(v_int) == hasher(100LL));
    assert(eq(v_int, 100LL));
    assert(hasher(v_text) == hasher("hello"));
    assert(eq(v_text, "hello"));

    // Standard find with key_type in C++14:
    assert(umap.find(SqliteValueOwned(100LL)) != umap.end() && umap.find(SqliteValueOwned(100LL))->second == 1);
    assert(umap.find(v_int.to_owned()) != umap.end() && umap.find(v_int.to_owned())->second == 1);
    assert(umap.find(SqliteValueOwned::from_text("hello")) != umap.end() && umap.find(SqliteValueOwned::from_text("hello"))->second == 2);
    assert(umap.find(v_text.to_owned()) != umap.end() && umap.find(v_text.to_owned())->second == 2);
    assert(umap.find(SqliteValueOwned(3.14)) != umap.end() && umap.find(SqliteValueOwned(3.14))->second == 3);
    assert(umap.find(v_float.to_owned()) != umap.end() && umap.find(v_float.to_owned())->second == 3);
    assert(umap.find(v_long.to_owned()) != umap.end() && umap.find(v_long.to_owned())->second == 4);

    assert(umap.find(SqliteValueOwned(99LL)) == umap.end());
    assert(umap.find(SqliteValueOwned::from_text("world")) == umap.end());

#if __cplusplus >= 202002L
    // C++20 heterogeneous find: View & literals -> key
    assert(umap.find(v_int)   != umap.end() && umap.find(v_int)->second   == 1);
    assert(umap.find(v_text)  != umap.end() && umap.find(v_text)->second  == 2);
    assert(umap.find(v_float) != umap.end() && umap.find(v_float)->second == 3);
    assert(umap.find(v_long)  != umap.end() && umap.find(v_long)->second  == 4);
    assert(umap.find(100LL)   != umap.end() && umap.find(100LL)->second   == 1);
    assert(umap.find("hello") != umap.end() && umap.find("hello")->second == 2);
    assert(umap.find(99LL)    == umap.end());
    assert(umap.find("world") == umap.end());
#endif

    sqlite3_finalize(stmt);
}

/**
 * @brief Tests SqliteValueLess transparent functor as the comparator in std::map.
 */
void test_sqlite_value_less_functor() {
    printf("Testing SqliteValueLess Transparent Functor (std::map comparator)...\n");

    SqliteValueLess less;

    // NULL < INTEGER < FLOAT < TEXT < BLOB type ordering
    SqliteValueOwned null_val;
    SqliteValueOwned int_val(1LL);
    SqliteValueOwned float_val(1.0);
    SqliteValueOwned text_val("a");
    char bd[] = {0x01};
    SqliteValueOwned blob_val(SqliteBlobView(bd, 1));

    assert( less(null_val, int_val));
    assert(!less(int_val, null_val));
    assert( less(null_val, text_val));
    assert( less(null_val, blob_val));
    assert( less(int_val, text_val));
    assert( less(text_val, blob_val));

    // Strict typing tie-breaker: int(1) < float(1.0) within NUMERIC rank
    assert( less(int_val, float_val));
    assert(!less(float_val, int_val));

    // Same type, same value → not less
    assert(!less(int_val, int_val));
    assert(!less(null_val, null_val));

    // Use SqliteValueLess in std::map
    std::map<SqliteValueOwned, const char*, SqliteValueLess> ordered_map;
    ordered_map[SqliteValueOwned(10LL)]              = "ten";
    ordered_map[SqliteValueOwned(5LL)]               = "five";
    ordered_map[SqliteValueOwned::from_text("bar")]  = "bar_val";
    ordered_map[SqliteValueOwned::from_text("foo")]  = "foo_val";

    // Verify ordering: 5 < 10 < "bar" < "foo"
    auto it = ordered_map.begin();
    assert(it->first == 5LL);    ++it;
    assert(it->first == 10LL);   ++it;
    assert(it->first == "bar");  ++it;
    assert(it->first == "foo");
}

/**
 * @brief Tests SqliteValueEqual transparent functor across all type combinations.
 */
void test_sqlite_value_equal_functor(sqlite3* db) {
    printf("Testing SqliteValueEqual Transparent Functor (Heterogeneous Equality)...\n");

    SqliteValueEqual eq;

    // int vs view
    sqlite3_stmt* stmt = nullptr;
    assert(sqlite3_prepare_v2(db, "SELECT 42, 'hello', 3.14;", -1, &stmt, nullptr) == SQLITE_OK);
    assert(sqlite3_step(stmt) == SQLITE_ROW);

    SqliteValueView v_int   = SqliteValueView::from_column(stmt, 0);
    SqliteValueView v_text  = SqliteValueView::from_column(stmt, 1);
    SqliteValueView v_float = SqliteValueView::from_column(stmt, 2);

    SqliteValueOwned o_int(42LL);
    SqliteValueOwned o_text  = SqliteValueOwned::from_text("hello");
    SqliteValueOwned o_float(3.14);

    // Owned == Owned
    assert(eq(o_int, o_int));
    assert(eq(o_text, o_text));
    assert(!eq(o_int, o_text));

    // Owned == View
    assert(eq(o_int, v_int));
    assert(eq(o_text, v_text));
    assert(eq(o_float, v_float));

    // View == Owned (symmetric)
    assert(eq(v_int, o_int));
    assert(eq(v_text, o_text));

    // Primitive comparisons via functor
    assert(eq(o_int, 42LL));
    assert(eq(v_int, 42LL));
    assert(eq(o_text, "hello"));
    assert(eq(v_text, "hello"));

    // Type mismatch → not equal
    assert(!eq(o_int, 42.0));   // INTEGER != FLOAT
    assert(!eq(o_int, "42"));   // INTEGER != TEXT
    assert(!eq(o_text, o_float));

    sqlite3_finalize(stmt);
}

int main() {
    printf("================================================================\n");
    printf("RUNNING SQLITE VALUE STD TESTS (Transparent Hashing & STL Map)\n");
    printf("================================================================\n");

    sqlite3_initialize();
    sqlite3* db = nullptr;
    assert(sqlite3_open(":memory:", &db) == SQLITE_OK);

    test_transparent_hashing(db);

    // NEW TESTS
    test_hash_scalar_overloads();
    test_unordered_map_heterogeneous(db);
    test_sqlite_value_less_functor();
    test_sqlite_value_equal_functor(db);

    sqlite3_close(db);
    sqlite3_shutdown();

    printf("================================================================\n");
    printf("ALL SQLITE VALUE STD TESTS PASSED SUCCESSFULLY!\n");
    printf("================================================================\n");
    return 0;
}

